"""Typed dialogue state and repository foundation."""

from application.dialogue.errors import (
    AmbiguousSelection,
    ConfirmationAlreadyConsumed,
    ConfirmationExpired,
    ConfirmationMismatch,
    DialogueError,
    ExpiredContext,
    InvalidDialogueTransition,
    InvalidDialogueValue,
    InvalidSelection,
    NavigationLoop,
    NoPendingOperation,
    OperationAlreadyConsumed,
    OperationCancelled,
    OperationExpired,
    PendingOperationExists,
    SessionNotFound,
    StaleResultSet,
    SlotExpired,
    VersionConflict,
)
from application.dialogue.memory_repository import InMemoryDialogueSessionRepository
from application.dialogue.models import (
    ActiveResultSet,
    ClientSessionIdentity,
    ConfirmationRequest,
    ConfirmationStatus,
    CreateFolderParameters,
    DialogueSession,
    DialogueState,
    ExperienceMode,
    FileSelectionBehavior,
    FolderLocation,
    ItemKind,
    OperationRiskLevel,
    OperationTargetSnapshot,
    OperationType,
    PendingOperation,
    PendingOperationStatus,
    ResultItem,
    SelectedItemReference,
    SlotRequest,
)
from application.dialogue.repository import DialogueSessionRepository
from application.dialogue.service import DialogueSessionService

__all__ = [
    "ActiveResultSet",
    "AmbiguousSelection",
    "ClientSessionIdentity",
    "ConfirmationAlreadyConsumed",
    "ConfirmationExpired",
    "ConfirmationMismatch",
    "ConfirmationRequest",
    "ConfirmationStatus",
    "CreateFolderParameters",
    "DialogueError",
    "DialogueSession",
    "DialogueSessionRepository",
    "DialogueSessionService",
    "DialogueState",
    "ExperienceMode",
    "ExpiredContext",
    "FileSelectionBehavior",
    "FolderLocation",
    "InMemoryDialogueSessionRepository",
    "InvalidDialogueValue",
    "InvalidDialogueTransition",
    "InvalidSelection",
    "ItemKind",
    "NavigationLoop",
    "NoPendingOperation",
    "OperationAlreadyConsumed",
    "OperationCancelled",
    "OperationExpired",
    "OperationRiskLevel",
    "OperationTargetSnapshot",
    "OperationType",
    "PendingOperation",
    "PendingOperationExists",
    "PendingOperationStatus",
    "ResultItem",
    "SelectedItemReference",
    "SessionNotFound",
    "SlotExpired",
    "SlotRequest",
    "StaleResultSet",
    "VersionConflict",
]
